#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#dotnet format --check
#if [ $? -ne 0 ]; then
#    echo "Code formatting failed, please fix the issues and commit again."
#    exit 1
#fi

# Add this block to run CSharpier
#dotnet csharpier --check --config-path ./csharpier.json ./Shared.Abstractions ./Grains ./WebApiClient ./SiloHost
#if [ $? -ne 0 ]; then
#    echo "CSharpier formatting failed, please fix the issues and commit again."
#    exit 1
#fi

dotnet build
if [ $? -ne 0 ]; then
    echo "Linting failed, please fix the issues and commit again."
    exit 1
fi