name: Build

on:
  pull_request:
  push:
    branches: ["develop"]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        servicename: [SiloHost, WebApiClient]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: dotnet publish ${{ matrix.servicename }}/${{ matrix.servicename }}.csproj -o out/${{ matrix.servicename }}
