name: Test

on:
  push:
    branches: ["ci-experiment"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASPNETCORE_ENVIRONMENT: Development
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y curl jq net-tools
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Test
        run: |
          cd SiloHost
          dotnet run > silo.log 2>&1 &
          cd ../WebApiClient
          dotnet run > webapi.log 2>&1 &
          sleep 10
          cd ..
          bash scripts/set-config.sh
          bash scripts/add-api-key.sh
          bash scripts/generate-image.sh
